name: Test html
on: [push]
jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: bash ./test_html.sh
