name: Test html
on:
push:
jobs:
  test-html:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run tests
        run: bash ./test_html.sh
